apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xr1znxynl-java-quarkus 
  janus-idp.io/tekton: xr1znxynl-java-quarkus
  backstage.io/kubernetes-id: xr1znxynl-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xr1znxynl-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml