apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xr1znxynl-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xr1znxynl-java-quarkus-gitops